# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: commonCommands

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "=1.15.3"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  profile: TradeIT
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource: arn:aws:dynamodb:*:*:table/event-source
      -  Effect: "Allow"
         Action:
           - "sns:publish"
         Resource: "arn:aws:sns:ap-southeast-2:296927073230:*"
      -  Effect: "Allow"
         Action:
           - "sns:subscribe"
         Resource: "arn:aws:sns:ap-southeast-2:296927073230:GeneralCommandSNSTopic"
          
functions:
  entityCommandHandler:
    handler: handler.entityCommandHandler
    events:
      - sns: arn:aws:sns:ap-southeast-2:296927073230:GeneralCommandSNSTopic
  commandHandler:
    handler: handler.commandHandler
    events: # The Events that trigger this Function
      - http:
          path: tradeit/command
          method: post
  eventHandler:
    handler: handler.eventHandler   
    events:
      - stream:
          type: dynamodb
          arn: 
            Fn::GetAtt:
              - EventSource
              - StreamArn   
          batchSize: 100
          startingPosition: LATEST
          enabled: true

resources:  
  Resources:
    GeneralCommandSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'General Common Message Dispacher'
        TopicName: GeneralCommandSNSTopic
    NotificationSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'Notification Message Dispacher'
        TopicName: NotificationSNSTopic
    DocumentationSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'Documentation Message Dispacher'
        TopicName: DocumentationSNSTopic
    UserGroupSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'UserGroup Message Dispacher'
        TopicName: UserGroupSNSTopic
    TransactionSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'Transaction Message Dispacher'
        TopicName: TransactionSNSTopic
    BuyerSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'Buyer Message Dispacher'
        TopicName: BuyerSNSTopic
    SellerSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'Seller Message Dispacher'
        TopicName: SellerSNSTopic
    IssuingBankSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'IssuingBank Message Dispacher'
        TopicName: IssuingBankSNSTopic
    AdvisingBankSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'AdvisingBank Message Dispacher'
        TopicName: AdvisingBankSNSTopic
    DeNormalizerSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: 'DeNormalizer Message Dispacher'
        TopicName: DeNormalizerSNSTopic
    EventSource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: event-source
        AttributeDefinitions:
          - AttributeName: sequence
            AttributeType: N
        KeySchema:
          - AttributeName: sequence
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    
